---

- name: Install httpd
  ansible.builtin.dnf:
    name: httpd
    state: present

- name: Corrupt Listen directive in httpd config
  ansible.builtin.replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen'
    replace: 'LListen'

- name: Start httpd service (will fail due to bad config)
  ansible.builtin.service:
    name: httpd
    state: started
  ignore_errors: true