---

# -------------------------------------------------
# Default Variables
# -------------------------------------------------
# REQUIRED: Must be set by user or will fail
insights_host_org: "{{ insights_org | mandatory }}"
insights_host_activation_key: "{{ insights_activation_key | mandatory }}"
