---

# -------------------------------------------------
# Default Variables
# -------------------------------------------------
insights_host_org: <CHANGEME>
insights_host_activation_key: <CHANGEME>
