---
galaxy_info:
  role_name: mcp_host
  author: Mitesh Sharma (mitsharm@redhat.com)
  description: Configure mcp host
  license: GPLv3
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - 8
        - 9
  galaxy_tags:
    - rhel
    - satellite
    - mcp
    - podman
    - management
    - redhat
dependencies: []