---
- name: Configure satellite admin password
  ansible.builtin.command: "foreman-rake permissions:reset password={{ satellite_reconfigure_new_admin_password }}"

- name: Update hammer admin password in /root/.hammer/cli.modules.d/foreman.yml
  ansible.builtin.lineinfile:
    path: /root/.hammer/cli.modules.d/foreman.yml
    regexp: 'password'
    line: "  :password: '{{ satellite_reconfigure_new_admin_password }}'"

- name: Check if fapolicyd rules file exists
  ansible.builtin.stat:
    path: "/etc/fapolicyd/rules.d/30-patterns.rules"
  register: file_data

- name: Change satellite hostname
  ansible.builtin.shell: >-
    satellite-change-hostname {{ satellite_reconfigure_new_hostname }}
    -u {{ satellite_reconfigure_username }} -p '{{ satellite_reconfigure_new_admin_password }}' --skip-dns --assumeyes
  register: satellite_change_hostname
  failed_when: '"Success!" not in satellite_change_hostname.stdout'

- name: Refresh the manifest
  ansible.builtin.command: 'hammer subscription refresh-manifest --organization="{{ satellite_reconfigure_org }}"'
