---
galaxy_info:
  role_name: satellite_host
  author: Mitesh Sharma (mitsharm@redhat.com)
  description: Register and configure Satellite host
  license: GPLv3
  min_ansible_version: "2.9"
  platforms: []
  galaxy_tags: []
dependencies: []