---
# -------------------------------------------------
# Default Variables
# -------------------------------------------------
satellite_reconfigure_external_fqdn: "{{ groups['satellites'][0].split('.')[0] }}-{{ subdomain }}"
satellite_reconfigure_internal_fqdn: satellite.lab
satellite_reconfigure_user_name: admin
satellite_reconfigure_user_password: <CHANGEME>
