---
# -------------------------------------------------
# Default Variables
# -------------------------------------------------
satellite_host_katello_ca_rpm: http://satellite-{{ subdomain }}/pub/katello-ca-consumer-latest.noarch.rpm
satellite_host_org: <CHANGEME>
satellite_host_activation_key: <CHANGEME>
satellite_host_verify_ssl: true
