---
galaxy_info:
  role_name: break_httpd
  author: Mitesh Sharma (mitsharm@redhat.com)
  description: Break the Apache
  license: GPLv3
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags: []
dependencies: []
